# Generated by Django 5.0.1 on 2024-04-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phoneno', models.PositiveIntegerField(default=None)),
                ('idno', models.PositiveIntegerField(default=None)),
                ('krapin', models.CharField(max_length=150)),
            ],
        ),
    ]
