# Generated by Django 5.0.1 on 2024-04-17 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=150)),
                ('invamt', models.PositiveIntegerField(default=None)),
                ('cardetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.stock')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.prospects')),
            ],
        ),
    ]
