# Generated by Django 5.0.1 on 2024-04-17 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt_paid', models.PositiveIntegerField(default=0)),
                ('payment_mode', models.CharField(choices=[('MPESA ', 'Mpesa'), ('CASH ', 'Cash'), ('CHEQUE', 'Cheque'), ('BANK-TRANSACTION', 'Bank Payment')], default='Mpesa', max_length=20)),
                ('invamount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.business')),
            ],
        ),
    ]
