# Generated by Django 5.0.1 on 2024-04-17 07:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='paymentdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
