# Generated by Django 5.0.1 on 2024-04-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_receipt_paymentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='invamt',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
