# Generated by Django 5.0.1 on 2024-04-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_business_invamt'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='engine',
            field=models.CharField(default='1190CC', max_length=150),
        ),
        migrations.AddField(
            model_name='business',
            name='fuel',
            field=models.CharField(choices=[('PETROL ', 'Petro'), ('DIESEL ', 'Diesel')], default='Petrol', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='business',
            name='transmission',
            field=models.CharField(choices=[('AUTOMATIC ', 'Automatic'), ('MANUAL ', 'Manual')], default='Automatic', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='ttlamt',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
