# Generated by Django 5.0.1 on 2024-05-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_business_engine_business_fuel_business_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospects',
            name='pobox',
            field=models.CharField(default='NONE', max_length=150),
        ),
        migrations.AlterField(
            model_name='business',
            name='fuel',
            field=models.CharField(choices=[('PETROL ', 'Petrol'), ('DIESEL ', 'Diesel')], default='Petrol', max_length=20),
        ),
    ]
