# Generated by Django 5.0.1 on 2024-07-17 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_prospects_pobox_alter_business_fuel'),
        ('inventory', '0002_remove_carexpenses_chassisno_alter_carexpenses_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='cardetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.carexpenses'),
        ),
    ]
