# Generated by Django 5.0.1 on 2024-07-18 07:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_business_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
