# Generated by Django 5.0.1 on 2024-04-15 12:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceno', models.CharField(max_length=30)),
                ('invoiceamt', models.IntegerField(default=0)),
                ('amtpaid', models.IntegerField(default=0)),
                ('datepaid', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.carmake')),
            ],
            options={
                'unique_together': {('make', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CarExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalcost', models.PositiveIntegerField(default='0')),
                ('chassisno', models.CharField(default='0001', max_length=50)),
                ('unitcost', models.PositiveIntegerField(default='0')),
                ('tax', models.PositiveIntegerField(default='0')),
                ('portcharges', models.PositiveIntegerField(default='0')),
                ('transportcharges', models.PositiveIntegerField(default='0')),
                ('miscellaneous', models.PositiveIntegerField(default='0')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='JapanStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassisno', models.CharField(max_length=50)),
                ('cif', models.PositiveIntegerField(default=0)),
                ('exchangerate', models.PositiveIntegerField(default=1)),
                ('paymentdate', models.DateField(default=django.utils.timezone.now)),
                ('totalcost', models.PositiveIntegerField(default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField(default=None)),
                ('chassisno', models.CharField(max_length=50)),
                ('arrivaldate', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('AVAILABLE ', 'AVAILABLE'), ('SOLD', 'SOLD')], default='AVAILABLE', max_length=20)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LeasedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=100)),
                ('contact', models.PositiveIntegerField(default=None)),
                ('showroom', models.CharField(max_length=150)),
                ('leasedate', models.DateField(default=django.utils.timezone.now)),
                ('cardetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stock')),
            ],
        ),
    ]
