# Generated by Django 5.0.1 on 2024-07-17 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carexpenses',
            name='chassisno',
        ),
        migrations.AlterField(
            model_name='carexpenses',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='chassisno',
            field=models.CharField(default='0001', max_length=50),
        ),
    ]
