# Generated by Django 5.0.1 on 2024-04-16 02:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
                ('officerent', models.PositiveIntegerField(default=0)),
                ('salary', models.PositiveIntegerField(default=0)),
                ('officeinternet', models.PositiveIntegerField(default=0)),
                ('miscellaneouscosts', models.PositiveIntegerField(default=0)),
                ('electricity', models.PositiveIntegerField(default=0)),
                ('paymentdate', models.DateField(default=django.utils.timezone.now)),
                ('totalcost', models.PositiveIntegerField(default='0')),
            ],
        ),
    ]
